apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: android-automation
spec:
  project: default
  source:
    repoURL: https://github.com/taufiq0205-test/pbapp-android-test.git
    path: argo
    targetRevision: feature/argocd
    kustomize:
      version: v4.5.7
  destination:
    server: https://kubernetes.default.svc
    namespace: android-tests
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true