apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appium-tests
spec:
  project: default
  source:
    repoURL: https://github.com/taufiq0205-test/pbapp-android-test.git
    path: k8s
    targetRevision: feature/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true