apiVersion: apps/v1
kind: Deployment
metadata:
  name: appium-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appium
  template:
    metadata:
      labels:
        app: appium
    spec:
      containers:
      - name: appium
        image: appium/appium:2.0
        ports:
        - containerPort: 4723
        command: ["appium"]
        args:
          - "--address"
          - "0.0.0.0"
          - "--port"
          - "4723"
          - "--relaxed-security"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        securityContext:
          privileged: true