apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-testing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taufiq0205-test/pbapp-android-test.git
    targetRevision: feature/argocd
    path: k8s/overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: mobile-testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true