apiVersion: batch/v1
kind: Job
metadata:
  name: medium-tests
spec:
  template:
    spec:
      containers:
      - name: test-runner
        image: autobots/pbapp-medium:latest
        env:
        - name: APPIUM_HOST
          value: "appium-server.android-tests.svc.cluster.local"
        - name: ANDROID_DEVICE
          value: "emulator-5554"
        securityContext:
          privileged: true
      restartPolicy: Never
      nodeSelector:
        device-type: android-emulator